### ISSUE TITLE
[BUG] `\degree` name collision with package `gensymb`

### ISSUE THREAD

**Issue by jcpaik** [meluso/UMich_Dissertation_Template#13]
I deeply appreciate you for this community effort that helps graduate students like me!

------------

**Describe the bug**
The command `\degree` is used by package `gensymb` to denote the degree symbol, like `30 \degree` for $30 \degree$.
However, this will be rewritten by `thesis-umich.cls`.
https://github.com/meluso/UMich_Dissertation_Template/blob/6844e69c675cccf3796b7e4417cfb39de68efe15/thesis-umich.cls#L289.

**To Reproduce**
Include package `gensymb` and use `30 \degree` in any part of your document.

**Possible resolution**
We can probably rename it to 'diploma', 'credential', 'degreetitle' or any suitable words that has only one meaning.

**Comment by meluso** [comment]
Noted! Sounds like you've got a fix figured out! If you'd like, you're welcome to propose the a pull request with 'degreetype' perhaps? That would be a big help!

**Comment by jcpaik** [comment]
@meluso Sure! I will make a PR tomorrow.

**Comment by meluso** [comment]
A picture of my bunny for you in gratitude! Thanks!

--


John Meluso (he/they)

Sloan VERSO Postdoctoral Fellow for Systems, Organizations, and Inclusion

Vermont Complex Systems Center at the University of Vermont

***@***.*** | www.johnmeluso.com<http://www.johnmeluso.com/>

________________________________

**Comment by meluso** [comment]
Promised bunny picture: https://photos.app.goo.gl/1gvZJEjGQ3UixfJJ7
Will merge shortly!
