### ISSUE TITLE
[FEATURE] Support specifying your legal name for the Identifier/Copyright Page

### ISSUE THREAD

**Issue by bryant1410** [meluso/UMich_Dissertation_Template#19]
**Is your feature request related to a problem? Please describe.**

[Rackham's Formatting Guidelines](https://rackham.umich.edu/navigating-your-degree/formatting-guidelines/) allow you to specify your preferred name on the title page but ask you to use your legal name for the next page (Identifier/Copyright Page).

Some people (including me) use different preferred and legal names.

**Describe the solution you'd like**

It'd be cool to have an option to set your legal name. It'd be used for the second page, while the first page would just use the usual `\author{...}` variable.

This new option could default to the `author` value so as not to break backward compatibility, and it's a sensible default value.

**Describe alternatives you've considered**

An alternative is not to support this at all. But I think it's cool to support this.

**Additional context**

Thanks for this project! By the way, I just did the Pre-defense Dissertation Review and all feedback I got was unrelated to this template (things like tables and other things I fucked up from the template myself). So this template is really solid!

**Comment by meluso** [comment]
Glad your predefense went well Santiago! This is a good idea, you're right; I'm sure plenty of folks will benefit from this feature.

I agree that it would be good to default to the `author` field if `legalname` is empty. I'll suggest changes in the pull request for this logic and the associated documentation.

**Comment by meluso** [comment]
Oh, my mistake! You've already set things up to default to the author's name and have added commenting to make it clear to users what their options are. Thank you!
