### ISSUE TITLE
Could you please explain how to define and use acronyms properly in this template? Thanks!

### ISSUE THREAD

**Issue by CreLox** [meluso/UMich_Dissertation_Template#2]

**Comment by meluso** [comment]
This... is a good question. Working on it! I know it uses the `\acro{}{}` command inside the \abbreviations{} command. So it would be something like this:

```
\acronyms{
    \acro{TLA}{Three Letter Acronym}
    \acro{SOA}{Some Other Acronym}
}
```

BUT, it's been a couple years and it's not displaying like I'd expect. So sit tight! If you happen to figure it out in the mean time, let me know!

**Comment by CreLox** [comment]
Thanks! That helps a lot. It would be really helpful if the `main.tex` template has examples like this.

The reason why they do not show up right away is probably that when `thesis-umich.cls` imports the `acronym` package, it specifies that
```TeX
\RequirePackage[printonlyused]{acronym}
```
Therefore, either the acronym has to be used properly (by syntaxes defined in the `acronym` package) in the text or `[printonlyused]` needs to be removed.

**Comment by meluso** [comment]
Huge help, that saved me a bunch of time, thank you! I've removed `[printonlyused]` so now your acronyms should appear. I've also added that example above to the template, and the Overleaf version will be updated shortly. I've added you to the contributors list for your help, thank you!
