### ISSUE TITLE
Consider adding the Creative Commons CC0 License

### ISSUE THREAD

**Issue by kelly-sovacool** [meluso/UMich_Dissertation_Template#5]
A few months back I first found [a different template](https://github.com/umangv/thesis-umich/issues/2) based on Derek Dalle's `thesis-umich.cls`. I wanted to fork and modify it for use with Quarto, but didn't feel it was right to do so since it did not have an open source license included. I reached out to Derek and he was supportive of adding a Creative Commons CC0 License. Since then I found this template and it appears to be more updated with recent changes to the Rackham guidelines.

Since this template is also a modified version of Derek's work, would you consider also adding a CC0 License? This way, others will be allowed to build upon your work.

**Comment by meluso** [comment]
Good idea, thanks. Added!

**Comment by kelly-sovacool** [comment]
Thanks @meluso! I now have a working Quarto extension using this class here: https://github.com/kelly-sovacool/rackham

And thanks to @samuelhansen for directing me to this template.
